"use client";

import { useState } from "react";

export default function TermsTabs() {
  const [activeTab, setActiveTab] = useState<"purchasing" | "sales">(
    "purchasing"
  );

  return (
    <>
      {/* Tab Navigation */}
      <div className="bg-gray-50 border-b border-gray-200 sticky top-[70px] z-40">
        <div className="max-w-3xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="flex overflow-x-auto">
            <button
              onClick={() => setActiveTab("purchasing")}
              className={`px-6 py-4 text-sm font-semibold whitespace-nowrap border-b-3 transition-colors ${
                activeTab === "purchasing"
                  ? "text-orange-600 border-orange-500 bg-white"
                  : "text-gray-500 border-transparent hover:text-gray-700"
              }`}
            >
              General Purchasing Conditions for Suppliers
            </button>
            <button
              onClick={() => setActiveTab("sales")}
              className={`px-6 py-4 text-sm font-semibold whitespace-nowrap border-b-3 transition-colors ${
                activeTab === "sales"
                  ? "text-orange-600 border-orange-500 bg-white"
                  : "text-gray-500 border-transparent hover:text-gray-700"
              }`}
            >
              General Conditions of Sale &amp; Delivery
            </button>
          </div>
        </div>
      </div>

      {/* Tab Content */}
      <section className="py-12 md:py-16">
        <div className="max-w-3xl mx-auto px-4 sm:px-6 lg:px-8">
          {activeTab === "purchasing" && (
            <div className="bg-white rounded-2xl shadow-sm border border-gray-100 p-8 md:p-12">
              <h2 className="text-xl font-bold text-gray-900 mb-6">
                General Purchasing Conditions for Suppliers of Tekpoint GmbH
              </h2>
              <h3 className="text-lg font-semibold text-gray-900 mt-8 mb-3">1. Conclusion of contract</h3>
              <p className="text-gray-700 leading-relaxed mb-4">All deliveries by the seller are affected on the basis of the following General Conditions of Sale and Delivery. Any changes or additional agreements require the written confirmation of the seller to become effective and only apply to the relevant individual transaction. The seller herewith objects to any deviating conditions of purchase of the purchaser; they are also not binding on the seller, even if the seller does not object to them again upon conclusion of the contract. The transmission of the order confirmation shall not be regarded as an acknowledgement of the purchaser’s conditions as well. The seller’s conditions are deemed to be accepted at the latest upon acceptance of the goods.</p>
              <h3 className="text-lg font-semibold text-gray-900 mt-8 mb-3">2. Change orders and order confirmation</h3>
              <p className="text-gray-700 leading-relaxed mb-4">Orders by the purchaser or amendments of such orders can be made by the purchaser in any oral, written or telephonic form. If an order confirmation is not given by the seller within a reasonable period (at the latest 7 days after receipt) in a written form, the purchaser is no longer bound to the purchase order. Until the receipt of such an order confirmation, the purchaser is entitled to withdraw from the order without giving reasons. Amendments of the order made by the seller shall be considered accepted only, if the purchaser accepts such amendments in a written form. In general such amendments do not bind the purchaser to approval and payment.</p>
              <h3 className="text-lg font-semibold text-gray-900 mt-8 mb-3">3. Offers</h3>
              <p className="text-gray-700 leading-relaxed mb-4">Offers of the seller are free of charge, even if the offer results from a request of the purchaser. This applies even if no purchase order results from the request. The seller is bound to his offers for minimum of two weeks after the purchaser’s receipt of the offer.</p>
              <h3 className="text-lg font-semibold text-gray-900 mt-8 mb-3">4. Prices</h3>
              <p className="text-gray-700 leading-relaxed mb-4">The prices indicated in the purchaser’s purchase orders are binding. Any price changes – irrespective of the reason – and prices which are not contained in the purchase order or which can only be notified after the purchase order must be acknowledged by the purchaser in writing. Unless agreed otherwise in the purchase order in writing, the agreed prices are free place of delivery exclusive VAT, including packaging, transport costs as well as all other expenses, costs, taxes and fees related to the purchase order.</p>
              <h3 className="text-lg font-semibold text-gray-900 mt-8 mb-3">5. Delivery period and acceptance</h3>
              <p className="text-gray-700 leading-relaxed mb-4">The agreed delivery dates are binding, except in cases of force majeure. The delivery period specified by the purchaser is calculated from the date of the purchase order. If no delivery or incomplete delivery is effected within this period, the purchaser has the right to cancel the contract without granting a grace period, without prejudice to the purchaser’s right to make damage claims. If the seller realizes that punctual delivery is impossible as a whole or in part, the seller is bound to notify the purchaser immediately in writing by specifying the reasons and the expected additional delivery period. The purchaser’s assessment shall be decisive for determining the delivered quantity, unless any assessment by the railway authorities is presented. Premature deliveries and/or partial delivery shall only be due upon written acceptance by the purchaser. Such deliveries shall not affect the purchaser’s term of payment. In any event the purchaser is not obliged to accept goods that are presented to the purchaser by the seller.</p>
              <h3 className="text-lg font-semibold text-gray-900 mt-8 mb-3">6. Non-competition clause</h3>
              <p className="text-gray-700 leading-relaxed mb-4">The seller guarantees that the purchased goods do not feature the same International Mobile Station Equipment Identity (IMEI) as goods already acquired by the purchaser. Otherwise the purchaser reserves the right of cancellation of or rescission from the contract.</p>
              <h3 className="text-lg font-semibold text-gray-900 mt-8 mb-3">7. Shipment</h3>
              <p className="text-gray-700 leading-relaxed mb-4">The shipment has to be sent to the address stipulated in the purchase order. Shipments may only be carried out by carriers and/or forwarders if the purchaser has explicitly agreed in writing. In general shipment instructions of the purchaser have to be followed by the seller. The seller is bound to notify the purchaser immediately of the dispatch of each shipment. A packing slip or delivery note, showing the purchaser’s purchase order number, is to be attached to the shipment. If such a packing slip or delivery note is not attached to the shipment, the purchaser reserves the right to deny the takeover and/or the payment of the shipment. The purchaser will only bear the costs of transportation insurance if this has been agreed upon explicitly in writing. In the event of border-crossing shipments, at least two invoices as customs documents and certificates of origin are to be included in the freight documents. All shipments that cannot be accepted due to non-compliance with the aforementioned shipment, customs or documentation provisions will be stored at the seller’s cost and risk until smooth handling of the transaction has become possible through the submission of proper documents. All risks, losses and costs resulting from a non-compliance with the aforementioned shipment, customs and documentation provisions shall be borne by the seller and the due date of invoice payment shall be extended accordingly based on the date of performance or submission of missing papers or documents. The purchaser reserves the right to deny the takeover of shipments, which are fraught with cash on delivery, cash advances or similar burdens.</p>
              <h3 className="text-lg font-semibold text-gray-900 mt-8 mb-3">8. Packaging</h3>
              <p className="text-gray-700 leading-relaxed mb-4">The seller is obliged to provide appropriate packaging based on the specific requirements of the goods and/or the type of shipment so that the proper arrival of the goods at the place of delivery is ensured. The packaging costs are included in the prices of the purchase order. The packaging itself must not be returned to the seller. Costs resulting from damage to the goods due to insufficient packaging shall be borne by the seller in any case.</p>
              <h3 className="text-lg font-semibold text-gray-900 mt-8 mb-3">9. Retention of title</h3>
              <p className="text-gray-700 leading-relaxed mb-4">The purchaser does not accept retention of title of the seller. Such retention of title are ineffective.</p>
              <h3 className="text-lg font-semibold text-gray-900 mt-8 mb-3">10. Passing of risk</h3>
              <p className="text-gray-700 leading-relaxed mb-4">The risk to the goods shall not pass to the purchaser before proper acceptance/takeover of the goods at the agreed place of delivery. Decisive for the proper takeover/acceptance is the confirmation by the competent institution/person of the purchaser, no matter if the receipt of the goods and/or the payment of the prices for the goods occurred before such a proper takeover/acceptance.</p>
              <h3 className="text-lg font-semibold text-gray-900 mt-8 mb-3">11. Notice of defects</h3>
              <p className="text-gray-700 leading-relaxed mb-4">The period for the review of the delivered goods with regard to amount, condition and quality as well as for the notice of possible defects is 4 weeks after the proper takeover/acceptance according to point 10. The notice period for hidden defects is 2 months after the discovery of such hidden defects, even if the aforementioned period of 4 weeks has expired. With respect to goods, which usually remain in the packaging until use, defects that become visible upon unpacking are regarded as hidden defects. The notice of defect by the purchaser is not bound to a specific form. The seller waives its right to the objection of a belated notice of defects.</p>
              <h3 className="text-lg font-semibold text-gray-900 mt-8 mb-3">12. Guarantee</h3>
              <p className="text-gray-700 leading-relaxed mb-4">The warranty period for products purchased from Tekpoint GmbH is at least 12 months from the date of purchase. The statutory warranty applies in full.</p>
              <h3 className="text-lg font-semibold text-gray-900 mt-8 mb-3">13. Liability</h3>
              <p className="text-gray-700 leading-relaxed mb-4">The seller is liable for all damages with regard to delayed and/or inadequate delivery. The seller is responsible for the adequate insurance of the delivery and the delivered goods and waives its rights to regress against the purchaser. The seller is obliged to indemnify the purchaser from and against any damage claims or product liability claims that may be asserted against the purchaser in connection with the goods. To the extent permissible under Austrian law (i.e., in cases of slight negligence and also in cases of simple gross negligence), the liability of the purchaser is expressly excluded. The purchaser and the seller shall purchase and sell the goods in compliance with existing national and international tax law. The seller undertakes to indemnify the purchaser from and against all claims regarding the non-compliance with these provisions, in particular with VAT law.</p>
              <h3 className="text-lg font-semibold text-gray-900 mt-8 mb-3">14. Property rights</h3>
              <p className="text-gray-700 leading-relaxed mb-4">The seller is responsible for not infringing the property rights of third parties in conjunction with the goods and is obliged to indemnify the purchaser from and against any claims that may be asserted against the purchaser in connection with such property rights.</p>
              <h3 className="text-lg font-semibold text-gray-900 mt-8 mb-3">15. Confidentiality clause</h3>
              <p className="text-gray-700 leading-relaxed mb-4">With regard to information brought to the attention of the seller in the performance of the order/delivery, the seller is ineligible to divulge this information to third parties or use them for their own benefit or that of any third party. The seller must keep this information confidentially, even after the delivery. The seller must transfer these obligations to all his subcontractors and employees.</p>
              <h3 className="text-lg font-semibold text-gray-900 mt-8 mb-3">16. Terms of payment and tax</h3>
              <p className="text-gray-700 leading-relaxed mb-4">The purchaser will pay the seller’s invoices only after the delivery of the complete order and at a discount of 3% within 30 days or net within 90 days. If the invoice is received later than the goods, the date of receipt of the invoice shall be decisive for calculating the payment periods pursuant to the paragraph above. In the event of any defects in the delivery, the purchaser is entitled to retain due payments. Payments made do not constitute an acknowledgement of the correctness of the delivery nor a waiver of any rights on the purchaser’s part. The purchaser is entitled to offsetting if any counter-claims exist. Any adjustments of this approach require in all cases the written consent of an authorised representative of the purchaser.</p>
              <h3 className="text-lg font-semibold text-gray-900 mt-8 mb-3">17. Order documents</h3>
              <p className="text-gray-700 leading-relaxed mb-4">Any drawings, drafts, models, etc. attached to the purchaser’s inquiries or purchase orders remain its property and are to be returned to the purchaser together with the quotation or after execution of the purchase order. These documents must not be made available to any third parties.</p>
              <h3 className="text-lg font-semibold text-gray-900 mt-8 mb-3">18. No transfer of rights</h3>
              <p className="text-gray-700 leading-relaxed mb-4">The transfer of the rights under the delivery contract to third parties without the purchasers’s consent is not permitted.</p>
              <h3 className="text-lg font-semibold text-gray-900 mt-8 mb-3">19. No offsetting</h3>
              <p className="text-gray-700 leading-relaxed mb-4">Offsetting with counter-claims against the purchaser’s claims is not permitted, unless the purchaser acknowledges such offsetting explicitly in writing in an individual case by specifying the amount.</p>
              <h3 className="text-lg font-semibold text-gray-900 mt-8 mb-3">20. Invalidity of individual provisions</h3>
              <p className="text-gray-700 leading-relaxed mb-4">If individual provisions of the General Conditions of Purchase are invalid, the validity of the remaining provisions of these General Conditions of Purchase and of the conclusion of contract shall not be affected.</p>
              <h3 className="text-lg font-semibold text-gray-900 mt-8 mb-3">21. Applicable law, place of performance, place of jurisdiction</h3>
              <p className="text-gray-700 leading-relaxed mb-4">The laws of the Republic of Austria shall be applicable. The provisions of the UNCITRAL Sales Convention of 1980 are excluded. The place of performance for delivery and payment shall be Vienna.The place of jurisdiction for all disputes under this contractual relationshipshall be the competent court in Vienna.</p>
            </div>
          )}

          {activeTab === "sales" && (
            <div className="bg-white rounded-2xl shadow-sm border border-gray-100 p-8 md:p-12">
              <h2 className="text-xl font-bold text-gray-900 mb-6">
                General Conditions of Sale and Delivery
              </h2>
              <h3 className="text-lg font-semibold text-gray-900 mt-8 mb-3">1. Conclusion of the contract</h3>
              <p className="text-gray-700 leading-relaxed mb-4">All deliveries by the seller are affected on the basis of the following General Conditions of Sale and Delivery. Any changes or additional agreements require the written confirmation of the seller to become effective and only apply to the relevant individual transaction. The seller herewith objects to any deviating conditions of purchase of the purchaser; they are also not binding on the seller, even if the seller does not object to them again upon conclusion of the contract. The transmission of the order confirmation shall not be regarded as an acknowledgement of the purchaser’s conditions as well. The seller’s conditions are deemed to be accepted at the latest upon acceptance of the goods.</p>
              <h3 className="text-lg font-semibold text-gray-900 mt-8 mb-3">2. Prices</h3>
              <p className="text-gray-700 leading-relaxed mb-4">Unless agreed otherwise, the selling prices applicable on the date of delivery are charged and any transportation or other incidental expenses are invoiced separately. Any discounts or rebates granted only apply to the respective delivery and not to any follow-up orders or deliveries, including if the seller does not object to any deductions made by the purchaser in the case of possible follow-up orders or deliveries. Unless otherwise agreed offers of the seller are not free of charge, if these offers result from a request of the purchaser and no purchase order results from this request.</p>
              <h3 className="text-lg font-semibold text-gray-900 mt-8 mb-3">3. Orders</h3>
              <p className="text-gray-700 leading-relaxed mb-4">Unless otherwise agreed, orders by the purchaser or amendments of such orders can be made by the purchaser in a written form only. The purchaser is bound to the order and is not entitled to withdraw from the order.</p>
              <h3 className="text-lg font-semibold text-gray-900 mt-8 mb-3">4. Terms of payment and tax</h3>
              <p className="text-gray-700 leading-relaxed mb-4">Unless agreed otherwise, the purchaser shall pay the seller’s invoices prior to delivery. In case of sale “On Hold” the following shall apply: After receipt of the agreed deposit payment the goods will be delivered to the forwarder/carrier mentioned in the offer. The forwarder/carrier keeps the goods in the name of the seller, until the purchaser has paid the goods in full and until the seller formally releases by a release letter (see point 4.) the goods. The forwarder/carrier is obliged to inspect the goods whether any goods are damaged or missing and to transmit an inspection report to the seller and to the purchaser. This inspection report shall be deemed as accurate, true and binding for both parties. However, in any case the seller is entitled to conduct an additional inspection of the goods or engage a third person to do so. After receipt of the inspection report the purchaser must affect payment in full. The full amount has to be credited to the agreed seller’s bank account within seven working days; otherwise, the seller is entitled to recall the goods and to demand a penalty up to 30% of the purchase price. In case the inspection report of the forwarder/carrier identifies damaged or missing goods the purchaser may claim a credit note in the amount of the damaged or missing goods. Cheques and bills of exchange are not accepted. If payment terms are not complied with, the seller is entitled, at its discretion (i) to charge interest on arrears of nine point two percentage points above the base rate, to demand, irrespective of a fault, the costs of extra-judicial recovery and collection measures and to claim damages for any losses incurred by the seller or (ii) to cancel the contract and claim damages due to non-performance. In the latter case the seller is entitled, irrespective of a fault of the purchaser, to demand or to retain the agreed down payment, but at least 15% of the purchase price, as a penalty. The duty to pay the penalty shall not impair the seller’s right to assert any additional losses. Payment periods granted commence on the date of invoicing. If payment periods are not met, the seller is also entitled to demand immediate payment of all of the claims the seller has against the purchaser. The purchaser and the seller shall purchase and sell the goods in compliance with existing national and international tax law. The purchaser undertakes to indemnify the seller from and against all claims regarding the non-compliance with these provisions, in particular with VAT law.</p>
              <h3 className="text-lg font-semibold text-gray-900 mt-8 mb-3">5. Delivery period and acceptance date</h3>
              <p className="text-gray-700 leading-relaxed mb-4">As a rule, the seller’s particulars regarding delivery dates are non-binding. The seller is not liable for any delays on the part of seller’s suppliers. The seller’s delivery obligation is subject to the reservation of correct and punctual deliveries from its suppliers, unless incorrect or non-punctual delivery from its suppliers is attributable to a fault on the seller’s part. Any claims of the purchaser for damages due to late performance are excluded. The purchaser is obliged to accept the goods immediately after a notification of their provision for delivery. In the event of late acceptance, the purchaser is liable to pay storage expenses without prejudice to any other rights the seller may have. Insofar as partial deliveries are possible, the seller may also affect partial deliveries at its option. Each partial delivery is regarded as a separate transaction and can be invoiced by the seller separately. With respect to mass-produced goods, the seller does not grant any warranty that the ordered quantity is absolutely complied with. Any excess items in the limits of usual tolerances are to be taken over by the purchaser at the same price. Delivery duties and delivery periods shall be suspended if the purchaser is late with a payment or fails to perform any other acts necessary for fulfilling the order. Any change in an order result in a change of the originally agreed delivery date. In case of sale “On Hold” the following shall apply: After receipt of the payment in full the seller shall send a release letter to the purchaser and the forwarder/carrier. The purchaser must sign the release letter and thereby agrees with the delivery of the goods according to the inspection report. The forwarder/carrier may only surrender the goods after the purchaser has presented the release letter signed by both seller and purchaser. A transfer of property only takes place after the forwarder/carrier has confirmed the delivery by signing the release letter and after the purchase price has been paid in full. The purchaser must collect the goods from the forwarder/carrier upon the release of goods. A partial release is not permitted. The forwarder/carrier may hold the goods up to a maximum of 14 days after receipt of the release letter signed by the seller. In case the purchaser does not collect the goods within this period or if the purchaser refuses acceptance of the goods the seller is entitled to recall the goods and to demand a penalty in the amount of 30% of the purchase price.</p>
              <h3 className="text-lg font-semibold text-gray-900 mt-8 mb-3">6. Shipment</h3>
              <p className="text-gray-700 leading-relaxed mb-4">Where no specific requirements regarding shipment have been defined in the purchase order, transportation is affected at the seller’s best discretion, but without any responsibility for the cheapest means of transportation. Shipment is affected exclusively at the risk of the purchaser, including in the event of freight-prepaid deliveries. Packaging material is invoiced at cost of sale and not taken back. Goods sent directly to third parties are regarded upon shipment as delivered in compliance with these terms and conditions and as accepted with respect to their outer and inner properties.</p>
              <h3 className="text-lg font-semibold text-gray-900 mt-8 mb-3">7. Reservation of title</h3>
              <p className="text-gray-700 leading-relaxed mb-4">The goods delivered remain the seller’s sole property until its total claim has been paid fully. The total claim means both its claim under the delivery of the goods and under the delivery of other goods or due to other legal reasons. The reservation of title only lapses after all of the seller’s claims have been paid by the purchaser. This also applies to a balance to the debit of the purchaser under a current account relationship. If the purchaser is late with payment, the seller is entitled to demand return of the goods at any time, including without cancelling the contract. Any legal action commenced regarding the purchase price or a part thereof shall not affect the seller’s reservation of title. If the seller’s reservation of title exists, the seller also has the right to cancel the contract. If the contract is cancelled, the purchaser will be credited only for the amount for the goods returned to the seller, which is the fair value of the goods on the date of return, less any handling expenses or transportation expenses incurred by the seller or other disadvantages caused by the cancellation of the contract, including lost profits. As long as the seller’s reservation of title is in existence, the purchaser may only dispose of the goods with the seller’s prior written consent. If the purchaser disposes of the seller’s goods, the seller automatically acquires all receivables and claims, which the purchaser accrues under the disposition of the goods. If the goods are commingled or processed, all resulting co-ownership claims shall be vested in the seller instead of in the purchaser. In the event of pledging of or any other claims to the delivered goods on the part of third parties, the purchaser shall notify the seller immediately. If the purchaser fails to pay the purchase price indicated in the invoice sent to the purchaser, including the value added tax stated, by the agreed due date, the purchaser shall secure the seller’s claim still outstanding by creating a sufficient lien, at its option, either on real property in the ownership of the purchaser, on items of tangible fixed assets, on investments held by the purchaser in third-party companies, on items of inventories, on bank balances with domestic credit institutions as well as on unconditional claims under contractual deliveries and services provided to customers with impeccable creditworthiness, in each case to the extent of the due purchase price claim.</p>
              <h3 className="text-lg font-semibold text-gray-900 mt-8 mb-3">8. No transfer of rights</h3>
              <p className="text-gray-700 leading-relaxed mb-4">The transfer of the rights under the delivery contract to third parties without the seller’s consent is not permitted.</p>
              <h3 className="text-lg font-semibold text-gray-900 mt-8 mb-3">9. Limited commercial guarantee and statutory implied warranty</h3>
              <p className="text-gray-700 leading-relaxed mb-4">The purchaser must inspect the goods immediately upon acceptance or arrival at the place of delivery, in the presence of the forwarder or transporter, in order to notify the seller immediately in writing if goods are damaged. If this does not happen, the goods are deemed to be free from defects, unless they are hidden defects. If the buyer becomes aware of a hidden defect, he must immediately inform the seller in writing. The commercial guarantee period depends on the product and purchase agreement. It could be 0 month, 12 month or 24 month. Equipment under which the manufacturer assumes the guarantee (instead of Tekpoint), the guarantee period may differ. The maximum commercial guarantee period ends 30 months after the sale of Tekpoint GmbH. The limited commercial guarantee and the legal warranty is processed by the buyer or the end customer via the manufacturer’s service centers. List of service centers is provided or can be requested via rma@tekpoint.com.</p>
              <p className="text-gray-700 leading-relaxed mb-4 font-semibold text-sm">THIS LIMITED COMMERCIAL GUARANTEE GIVES YOU SPECIFIC GUARANTEE RIGHTS. YOU MAY HAVE OTHER RIGHTS THAT ARE GIVEN BY LAW IN YOUR COUNTRY, PROVINCE OR STATE. IN SOME COUNTRIES, PROVINCES OR STATES CONSUMER LAW MAY SET A MINIMUM GUARANTEE PERIOD. THE LEGAL STATUTORY IMPLIED WARRANTY IS EXCLUDED. IN ORDER TO GET A FULL OVERVIEW OF YOUR RIGHTS, WE ARE HAPPY TO INVITE YOU TO KNOW THE LAWS OF YOUR COUNTRY.</p>
              <p className="text-gray-700 leading-relaxed mb-4">Tekpoint GmbH guarantees the first buyer that your product will be free from material and workmanship defects during normal use during the guarantee period. The limited commercial guarantee only applies if the product is used as specified in the instructions. Damage caused by the user and the following situations occurring are not covered by the guarantee:</p>
              <p className="text-gray-700 leading-relaxed mb-2 pl-4">• The product is damaged through negligence, fault, misuse or disaster on the part of the user (e.g., sticking of food or liquids, ingress of water, cracks due to external violence, scratches, and damage to peripheral components).</p>
              <p className="text-gray-700 leading-relaxed mb-2 pl-4">• The user himself disassembled, repaired or modified the device without having been authorized by the manufacturer (e.g., damage caused by a change in color, use of an additional part or unauthorized modification).</p>
              <p className="text-gray-700 leading-relaxed mb-2 pl-4">• The product will be damaged by connection to an unsuitable accessory or by transport or other accidents.</p>
              <p className="text-gray-700 leading-relaxed mb-2 pl-4">• The guarantee period has expired.</p>
              <p className="text-gray-700 leading-relaxed mb-2 pl-4">• No RMA number (Return Merchandise Authorization) has been requested or assigned by Tekpoint for the device.</p>
              <p className="text-gray-700 leading-relaxed mb-2 pl-4">• The product was returned without the original packaging and accessories, cables, charger, etc.</p>
              <p className="text-gray-700 leading-relaxed mb-2 pl-4">• The date of purchase cannot be checked and verified.</p>
              <p className="text-gray-700 leading-relaxed mb-2 pl-4">• The product was not sold from Tekpoint to the customer/retailer.</p>
              <p className="text-gray-700 leading-relaxed mb-2 pl-4">• This limited commercial guarantee does not apply to accessories and other consumables</p>
              <p className="text-gray-700 leading-relaxed mb-2 pl-4">• Please note, that a maximum of 10 products can be registered per RMA request/registration. If you would like to register more than 10 products, several RMA applications must be submitted. Unfortunately, applications with more than 10 devices must be automatically rejected.</p>
              <p className="text-gray-700 leading-relaxed mb-4">In the event of a defect, Tekpoint GmbH or the supplier of Tekpoint GmbH reserves the right to either repair, exchange the affected product or to issue a credit note for the latest purchase price. If the check reveals that the product sent in has no faults, Tekpoint GmbH reserves the right to charge a processing fee. The amount of the processing fee can be found on the RMA form, which must be filled out for every complaint. You will receive your RMA number under https://lightgate.tekpoint.com/rma or send your request to rma@tekpoint.com. You can obtain the manufacturer’s guarantee conditions from your contact in sales or send your request to rma@tekpoint.com There is no right of withdrawal of the buyer or cancellation of the contract. Section 933b of the Austrian General Civil Code (ABGB), which provides for a special right of recourse, does not apply. The seller will ship his deliveries within the scope and / or specifications of this document. Any obligations in addition to this framework agreement relating to specific qualifications, requirements and guarantee conditions in all cases require the written consent of an authorized representative of the seller.</p>
              <h3 className="text-lg font-semibold text-gray-900 mt-8 mb-3">10. Damage claims and resale</h3>
              <p className="text-gray-700 leading-relaxed mb-4">The seller is liable only for an intentional or grossly negligent conduct on its part. Damage claims, in particular those made instead of warranty claims, are statute-barred after six months from the date on which the purchaser has become aware of the damage and the party causing the damage. If the purchaser or any other of the seller’s contracting partner resells the products placed on the market or distributed by the seller, the purchaser or partner is obliged to impose the afore-mentioned regulation to its full extent on its customers and to obligate them to impose it further on all their customers. The purchaser or any other of the seller’s contracting partner shall be liable for all disadvantages the seller incurs if they fail to further impose the aforementioned regulation. Resale means any transfer of the goods as a whole or part of the goods to another purchaser, whether in unprocessed or processed form. The purchaser may only resale the goods purchased from the seller to purchasers that are located in countries, in which a use of goods in compliance with the relevant provisions is permitted. Failing this, the purchaser undertakes to indemnify the seller from and against all claims regarding the non- compliance with these provisions.</p>
              <h3 className="text-lg font-semibold text-gray-900 mt-8 mb-3">11. No offsetting</h3>
              <p className="text-gray-700 leading-relaxed mb-4">Offsetting with counterclaims against the seller’s claims is not permitted unless the seller acknowledges such offsetting explicitly in writing in an individual case by specifying the amount.</p>
              <h3 className="text-lg font-semibold text-gray-900 mt-8 mb-3">12. Release from the performance of contracts concluded</h3>
              <p className="text-gray-700 leading-relaxed mb-4">Any events of force majeure and their consequences shall release the seller from its duty to deliver. Changes in the purchaser’s creditworthiness give the seller the right to cancel the purchase or to request payment in advance or securities. In this case, the purchaser shall be liable for expenses incurred by the seller in connection with the order placed. Damage claims made by the purchaser due to these reasons are excluded.</p>
              <h3 className="text-lg font-semibold text-gray-900 mt-8 mb-3">13. Property rights</h3>
              <p className="text-gray-700 leading-relaxed mb-4">The purchaser is responsible for not infringing the property rights of third parties in conjunction with the goods and is obliged to indemnify the seller from and against any claims that may be asserted against the seller in connection with such property rights.</p>
              <h3 className="text-lg font-semibold text-gray-900 mt-8 mb-3">14. Confidentiality clause</h3>
              <p className="text-gray-700 leading-relaxed mb-4">Regarding information brought to the attention of the purchaser in the performance of the order/delivery, the purchaser is ineligible to divulge this information to third parties or use them for their own benefit or that of any third party. The purchaser must keep this information confidentially, also after the delivery. The purchaser must transfer these obligations to all his subcontractors and employees.</p>
              <h3 className="text-lg font-semibold text-gray-900 mt-8 mb-3">15. Invalidity of individual provisions</h3>
              <p className="text-gray-700 leading-relaxed mb-4">If individual provisions of these General Conditions of Sale and Delivery are invalid, the validity of the remaining provisions of these General Conditions of Sale and Delivery and of the conclusion of contract shall not be affected.</p>
              <h3 className="text-lg font-semibold text-gray-900 mt-8 mb-3">16. Applicable law, place of performance and place of jurisdiction</h3>
              <p className="text-gray-700 leading-relaxed mb-4">The laws of the Republic of Austria shall be applicable. The provisions of the UNCITRAL Sales Convention of 1980 are excluded. The place of performance for delivery and payment shall be Vienna. The place of jurisdiction for all disputes under this contractual relationship shall be the competent court in Vienna.</p>
            </div>
          )}
        </div>
      </section>
    </>
  );
}
